#!/usr/bin/env sh
set -e

tmp="$(dirname "$(readlink -f -- "$0")")/tmp"

mkdir -p "$tmp/extracted"

# https://github.com/ryanoasis/nerd-fonts/releases
curl https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/SourceCodePro.tar.xz -LO --output-dir "$tmp"
tar -xf "$tmp/SourceCodePro.tar.xz" -C "$tmp/extracted/"

# use the standard variants, there are also monospaced (NerdFontMono) and proportional (NerdFontPropo)
find tmp/extracted -iname '*NerdFont-*' -exec cp {} ./ \;
rm -rf "$tmp"
