#!/usr/bin/env bash
sshp_lp_usage() {
    echo "Usage:"
    echo "\t sshlp <local_port> <ssh options>"
    echo ""
    echo "Example:"
    echo "sshlp 8888 user@jump.host.tld -p 222"
}

# uses sshp to start a local socks proxy to pass traffic through an ssh tunnel
# usage: sshp 8888 jump.host.tld -p 222
# usage: sshp <local_proxy_port> <ssh params>
sshlp() {
    local_port="$1"
    if [ -z "$local_port" ]; then
        sshlp_usage
    fi
    shift

    echo "Starting ssh socks proxy on localhost:$local_port"
    echo "Urls:"
    echo "- socks4://localhost:$local_port"
    echo "- socks5://localhost:$local_port"
    echo ""

    sshp -ND "localhost:$local_port"
}
