# load customizations first, on macos this file might set up tooling we
# need.
if [ -f "$HOME/.zshrc.local" ]; then
    source "$HOME/.zshrc.local"
fi

. "$HOME/.config/setup/env-early.sh"

if hash direnv 2>/dev/null; then
    emulate zsh -c "$(direnv export zsh)"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if hash direnv 2>/dev/null; then
    emulate zsh -c "$(direnv hook zsh)"
fi

source ~/.config/zsh-plugins/powerlevel10k/powerlevel10k.zsh-theme

. "$HOME/.config/setup/ssh.sh"
. "$HOME/.config/setup/tools.sh"
. "$HOME/.config/bashrc.d/z.sh"

if [ -d "$HOME/.config/zshrc.d/" ] ; then
    for file in "$HOME/.config/"zshrc.d/* ; do
        source "$file"
    done
    unset -v file
fi

. "$HOME/.config/setup/env.sh"

setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# vi mode
bindkey -v
bindkey '^?' backward-delete-char
#bindkey '^h' backward-delete-char
# prevent timeout when pressing esc
export KEYTIMEOUT=1

# I like the bash behaviour of globbing
unsetopt extended_glob
setopt +o nomatch
# Disable XON/XOFF flow control
unsetopt flowcontrol

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/.config/zsh-plugins/zsh_syntax_highlighting/zsh-syntax-highlighting.zsh
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets root)
