# Make sure the shell is interactive
case $- in
    *i*) ;;
    *) return ;;
esac

# Disable XON/XOFF flow control
stty -ixon

. "$HOME/.config/setup/ssh.sh"
. "$HOME/.config/setup/tools.sh"

# Load bash scripts
if [ -d "$HOME/.config/bashrc.d" ] ; then
    for file in "$HOME/.config"/bashrc.d/* ; do
        . "$file"
    done
    unset -v file
fi

if hash direnv 2>/dev/null; then
    eval "$(direnv hook bash)"
fi

if type brew &>/dev/null && [ ! -z "$BASH_VERSION" ]; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            [[ -r "$COMPLETION" ]] && source "$COMPLETION"
        done
    fi
fi

# Add NVM bash completion
if [ -d "$HOME/.nvm" ]; then
    if [ -s "$NVM_DIR/bash_completion" ]; then
        \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    fi
fi

. "$HOME/.config/setup/env.sh"
