# Make sure the shell is interactive
case $- in
    *i*) ;;
    *) return ;;
esac

# Disable XON/XOFF flow control
test -z "$ZSH_VERSION" && stty -ixon

# Load posix scripts
if [ -d "$HOME/.config/shrc.d/" ]; then
    for file in "$HOME"/.config/shrc.d/* ; do
        . "$file"
    done
    unset -v file
fi

# Load bash scripts
if [ -d "$HOME/.config/bashrc.d" ] ; then
    for file in "$HOME/.config"/bashrc.d/* ; do
        . "$file"
    done
    unset -v file
fi

# source sdkman if it's installed
if [ -f "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
    . "$HOME/.sdkman/bin/sdkman-init.sh"
fi

# Add RVM to PATH
export PATH="$PATH:$HOME/.rvm/bin"

# Add NVM
export NVM_DIR="$HOME/.nvm"
# use ifs to prevent non zero exit state if nvm is not installed
if [ -s "$NVM_DIR/nvm.sh" ]; then
    \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi
if [ -s "$NVM_DIR/bash_completion" ]; then
    \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi
