# set PATH to include the private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# source local bash_profile if exists
if [ -f "$HOME/.bash_profile.local" ]; then
    . "$HOME/.bash_profile.local"
fi

# source interactive bash config
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

