# vim: ft=sh
# set PATH to include the private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin"
fi

# set PATH to include the global composer bin if it exists
if [ -d "$HOME/.composer/vendor/bin" ]; then
    PATH="$PATH:$HOME/.composer/vendor/bin"
fi

# Setup EDITOR and VISUAL
if hash vim 2>/dev/null; then
    export EDITOR="vim"
    export VISUAL="$EDITOR"
else
    echo "Dude, no vim?!"
fi

# source local bash_profile if exists
if [ -f "$HOME/.bash_profile.local" ]; then
    . "$HOME/.bash_profile.local"
fi

# source interactive bash config
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
