# vim: ft=bash

# source local bash_profile if exists
if [ -f "$HOME/.bash_profile.local" ]; then
    . "$HOME/.bash_profile.local"
fi

# source interactive bash config
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
